#!name=xjh51 香蕉视频
#!desc=VIP 视频解锁 + 去广告 + 外部播放器
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
# API 拦截
^https?:\/\/www\.xjh51\.tv\/api\/(?:init|index|ucp\/index|v2\/vod\/(?:reqplay|listing)|vod\/(?:reqplay|show)|getLikeRows|special\/listing|game\/broadcasts) url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/xjh51/dist/xjh51.js

# 前端处理
^https?:\/\/www\.xjh51\.tv\/(?:index|pc)\.html url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/xjh51/dist/xjh51-frontend.js

[mitm]
hostname = www.xjh51.tv
