#!name=妻友社区解锁
#!desc=VIP 解锁 + 去广告 + 完整 m3u8 + 第三方播放器跳转
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?:\/\/d1kmvkv4iwtiup\.cloudfront\.net\/api\/app\/(ping\/config|login\/guest|user\/info|media\/(play|home|short\/hot)|card\/(promotion|list|advance\/status)) url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/qiyoushe/dist/qiyoushequ.js

[mitm]
hostname = *.cloudfront.net, *.gcwe44p.com
