#!name=幻宇星球 VIP 解锁
#!desc=解锁 VIP
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?://(?:huanyuxingqiu\.\w+|daoyu\.\w+|hyxq\w*\.\w+)/(?!.*\.(?:png|jpe?g|gif|webp|svg|ico|css|js|woff2?|ttf|eot|mp[34]|zip|rar)(?:\?|$)) url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/huanyu/dist/response.js

[mitm]
hostname = huanyuxingqiu.*, daoyu.*, hyxq*.*
