#!name=幻宇星球 VIP 解锁
#!desc=解锁 VIP
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?://(?:daoyu\.fan|huanyuxingqiu\.(?:vip|life)|hyxq666\.com) url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/huanyu/dist/response.js

[mitm]
hostname = daoyu.fan, huanyuxingqiu.vip, huanyuxingqiu.life, hyxq666.com
