#!name=JAVHD解锁VIP
#!desc=JAVHD视频解锁20260824
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?:\/\/(www\.|zh\.)?javhd\.com\/.*player_api url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/javhd/dist/javhd.js
^https?:\/\/(www\.|zh\.)?javhd\.com\/(zh\/studio\/room\/[\w-]+\/video\/[\w-]+|zh\/sex-categories|zh\/japanese-porn-videos|zh\/sex-videos|zh\/studio\/room|zh\/?$) url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/javhd/dist/javhd.js
^https?:\/\/(www\.|zh\.)?javhd\.com\/zh\/japanese-porn-videos\/category\/.+ url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/javhd/dist/javhd.js
^https?:\/\/(www\.|zh\.)?javhd\.com\/api\/.* url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/javhd/dist/javhd.js
^https?:\/\/.*\.cdnjhd\.com\/.*\.m3u8(\?.*)?$ url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/javhd/dist/javhd.js

[mitm]
hostname = javhd.com, www.javhd.com, zh.javhd.com, *.cdnjhd.com
