#!name=黄果短剧去广告
#!desc=去广告（播放跳转/轮播/横幅/贴片）
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?://huangguoai\.com url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/main/huangguoduanju/dist/huangguo.js
^https?://[^/]*adsdk[12]\.cc url reject

[mitm]
hostname = huangguoai.com, *.huangguoai.com, *.adsdk1.cc, *.adsdk2.cc
