[rewrite_local]
http://360.com/bilibili url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/BiliBili/BiliBili.Modified.response.js
[mitm]
hostname = 360.com
