#!name=insav 解锁
#!desc=VIP 解锁 + 去广告 + getVideoUrl Token 替换 + 第三方播放器跳转
#!author=@Jsforbaby
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?:\/\/(\w+\.)?(insav\.tv|[a-z]{4,}\d{2,}\.(top|com|net|cc|xyz))\/api\/(extend\/lists|banner\/lists|config\/lists|config\/links|notice\/lists|user\/(getVipStatus|info|login)|video\/(info|getVideoUrl)) url script-analyze-echo-response https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/insav-tv/dist/insav.js

[mitm]
hostname = insav.tv, 4k.insav.tv, dm.insav.tv, *.rftn469.com, *.pbfk364.com, *.rahc448.com, wuma.*.*
