import commonjs from "@rollup/plugin-commonjs";
import json from "@rollup/plugin-json";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import terser from "@rollup/plugin-terser";

export default [
	{
		input: "src/insav.js",
		output: {
			file: "dist/insav.js",
			format: "es",
			banner: "/* insav.js - VIP 解锁 + 去广告 + 播放器跳转 (script-analyze-echo-response) - Generated by Rollup */",
		},
		plugins: [json(), nodeResolve({ dedupe: ["@nsnanocat/util"] }), commonjs(), terser()],
	},
];
