#!name=海角视频解锁VIP
#!desc=海角视频20260822
#!author=Yu9191 Rewrite
#!homepage=https://github.com/Yu9191/Rewrite

[rewrite_local]
^https?:\/\/(www\.)?haijiao\.com\/api\/(banner\/banner_list|attachment|topic\/\d+) url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/haijiao/dist/haijiao.js
^https?:\/\/ts\d+\.hj\d+\.top\/.*\.m3u8$ url script-response-body https://raw.githubusercontent.com/Yu9191/Rewrite/refs/heads/main/haijiao/dist/haijiao.js

[mitm]
hostname = haijiao.com, www.haijiao.com, *.hj260302818.top
