name: 自动转换重写规则

on:
  push:
    paths:
      - '*.js'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2
        
      - name: 设置Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: 转换脚本
        run: |
          python .github/scripts/convert.py
          
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ReTra/Surge/*.sgmodule ReTra/Loon/*.plugin
          git commit -m "自动生成Surge模块和Loon插件 [skip ci]" || echo "没有文件需要提交"
          git push 